version: 2

models:

  - name: stg_localbike__brands
    description: "Staging model for product brands."
    columns:
      - name: brand_id
        description: "Primary key, unique identifier for each brand."
        tests:
          - unique:
              config:
                severity: warn
          - not_null:
              config:
                severity: warn
      - name: brand_name
        description: "Name of the brand."

  - name: stg_localbike__categories
    description: "Staging model for product categories."
    columns:
      - name: category_id
        tests:
          - unique:
              config:
                severity: warn
          - not_null:
              config:
                severity: warn
      - name: category_name

  - name: stg_localbike__customers
    description: "Staging model containing customer information."
    columns:
      - name: customer_id
        tests:
          - unique:
              config:
                severity: warn
          - not_null:
              config:
                severity: warn
      - name: email

  - name: stg_localbike__stores
    description: "Staging model containing store information."
    columns:
      - name: store_id
        tests:
          - unique:
              config:
                severity: warn
          - not_null:
              config:
                severity: warn

  - name: stg_localbike__staffs
    description: "Staging model containing staff information."
    columns:
      - name: staff_id
        tests:
          - unique:
              config:
                severity: warn
          - not_null:
              config:
                severity: warn
      - name: store_id

  - name: stg_localbike__products
    description: "Staging model containing product information."
    columns:
      - name: product_id
        tests:
          - unique:
              config:
                severity: warn
          - not_null:
              config:
                severity: warn
      - name: brand_id
      - name: category_id

  - name: stg_localbike__orders
    description: "Staging model containing order headers."
    columns:
      - name: order_id
        tests:
          - unique:
              config:
                severity: warn
          - not_null:
              config:
                severity: warn
      - name: customer_id
      - name: store_id
      - name: staff_id

  - name: stg_localbike__order_items
    description: "Staging model containing order line items."
    columns:
      - name: order_id
      - name: product_id

  - name: stg_localbike__stocks
    description: "Staging model containing stock levels per store and product."
    columns:
      - name: store_id
      - name: product_id
