version: 2

models:

  - name: stg_localbike__brands
    description: "Staging model for product brands."
    columns:
      - name: brand_id
        description: "Primary key, unique identifier for each brand."
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn
      - name: brand_name
        description: "Name of the brand."


  - name: stg_localbike__categories
    description: "Staging model for product categories."
    columns:
      - name: category_id
        description: "Primary key, unique identifier for each category."
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn
      - name: category_name
        description: "Name of the category."


  - name: stg_localbike__customers
    description: "Staging model containing customer information."
    columns:
      - name: customer_id
        description: "Primary key, unique identifier for each customer."
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn
      - name: email
        description: "Customer email address."


  - name: stg_localbike__stores
    description: "Staging model containing store information."
    columns:
      - name: store_id
        description: "Primary key, unique identifier for each store."
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn


  - name: stg_localbike__staffs
    description: "Staging model containing staff information."
    columns:
      - name: staff_id
        description: "Primary key, unique identifier for each staff member."
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn
      - name: store_id
        description: "Foreign key linking the staff to a store."
        tests:
          - relationships:
              name: store_id_foreign_key_in_stg_localbike__staffs
              to: ref('stg_localbike__stores')
              field: store_id
              severity: warn


  - name: stg_localbike__products
    description: "Staging model containing product information."
    columns:
      - name: product_id
        description: "Primary key, unique identifier for each product."
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn
      - name: brand_id
        description: "Foreign key linking product to brand."
        tests:
          - relationships:
              name: brand_id_foreign_key_in_stg_localbike__products
              to: ref('stg_localbike__brands')
              field: brand_id
              severity: warn
      - name: category_id
        description: "Foreign key linking product to category."
        tests:
          - relationships:
              name: category_id_foreign_key_in_stg_localbike__products
              to: ref('stg_localbike__categories')
              field: category_id
              severity: warn


  - name: stg_localbike__orders
    description: "Staging model containing order headers."
    columns:
      - name: order_id
        description: "Primary key, unique identifier for each order."
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn
      - name: customer_id
        description: "Foreign key linking order to customer."
        tests:
          - relationships:
              name: customer_id_foreign_key_in_stg_localbike__orders
              to: ref('stg_localbike__customers')
              field: customer_id
              severity: warn
      - name: store_id
        description: "Foreign key linking order to store."
        tests:
          - relationships:
              name: store_id_foreign_key_in_stg_localbike__orders
              to: ref('stg_localbike__stores')
              field: store_id
              severity: warn
      - name: staff_id
        description: "Foreign key linking order to staff."
        tests:
          - relationships:
              name: staff_id_foreign_key_in_stg_localbike__orders
              to: ref('stg_localbike__staffs')
              field: staff_id
              severity: warn


  - name: stg_localbike__order_items
    description: "Staging model containing order line items."
    columns:
      - name: order_id
        description: "Foreign key linking item to order."
        tests:
          - relationships:
              name: order_id_foreign_key_in_stg_localbike__order_items
              to: ref('stg_localbike__orders')
              field: order_id
              severity: warn
      - name: product_id
        description: "Foreign key linking item to product."
        tests:
          - relationships:
              name: product_id_foreign_key_in_stg_localbike__order_items
              to: ref('stg_localbike__products')
              field: product_id
              severity: warn


  - name: stg_localbike__stocks
    description: "Staging model containing stock levels per store and product."
    columns:
      - name: store_id
        description: "Foreign key linking stock to store."
        tests:
          - relationships:
              name: store_id_foreign_key_in_stg_localbike__stocks
              to: ref('stg_localbike__stores')
              field: store_id
              severity: warn
      - name: product_id
        description: "Foreign key linking stock to product."
        tests:
          - relationships:
              name: product_id_foreign_key_in_stg_localbike__stocks
              to: ref('stg_localbike__products')
              field: product_id
              severity: warn
