version: 2

models:
  - name: stg_airbnb__listings
    description: "Données brutes des annonces Airbnb pour analyse des prix par quartier"

    columns:
      - name: listing_id
        description: "Identifiant unique de l'annonce"
        tests:
          - unique
          - not_null

      - name: host_id
        description: "Identifiant unique de l'hôte de l'annonce"

      - name: neighbourhood_cleansed
        description: "Quartier où se situe l'annonce"

      - name: room_type
        description: "Type de logement (ex. : chambre privée, logement entier)"

      - name: price
        description: "Prix par nuit en USD"

      - name: minimum_nights
        description: "Nombre de nuits minimum pour une réservation"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 1
                max_value: 365
                strictly: false
              severity: warn

      - name: number_of_reviews
        description: "Nombre total de commentaires"

      - name: availability_365
        description: "Nombre de jours où le logement est disponible sur une année"
